name = "payload-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "MONGODB", class_name = "MongoDBDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["MongoDBDurableObject"]
