name = "payload-cloudflare"
main = "src/index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]
account_id = "b6641681fe423910342b9ffa1364c76d"

[durable_objects]
bindings = [
  { name = "MONGODB", class_name = "MongoDBDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["MongoDBDurableObject"]

[[r2_buckets]]
binding = "R2"
bucket_name = "payload-assets"
